Soc Kia
openWB/core pull request #1029
Opened 2023-07-11 22:39 UTC by Flock82

Initialer PR

Aktuell werden Werte anscheinend wegen eines versteckten Timeouts nicht übernommen.
(Auf {modules.common.store._api:26} - {DEBUG:soc_ev0} - Raw data CarState(soc=85, range=381.0, soc_timestamp=) folgt "Save state" nur, wenn das Ergebnis innerhalb weniger Sekunden vorliegt. Beim Kia-Modul muss aber alleine 130 Sekunden auf den Server gewartet werden.)

2023-07-12 18:36 UTC, Flock82 commented
Nein, keine Ahnung wo das herkommt. Das Timing lässt vermuten, dass es evtl. nicht mehr möglich ist, den Status zu setzen, sobald der nächste Regelungsdurchlauf stattfindet, das ist aber reine Vermutung.

2023-07-25 14:01 UTC, LKuemmel requested changes

2023-07-25 14:01 UTC, LKuemmel commented on packages/modules/vehicles/kia/api.py
> +                  response, exc_info=True)
```suggestion
        log.exception("kia.getDeviceId: Request device id failed")
```
Exceptions bitte immer loggen. Mit log.exception wird auch der Stack automatisch mitgeloggt. Bitte auch an den anderen Stellen anpassen.

2023-07-27 07:31 UTC, Flock82 commented on packages/modules/vehicles/kia/api.py
> +                  response, exc_info=True)
Ist entsprechend angepasst

2023-08-04 07:26 UTC, LKuemmel commented
Zu dem Timing-Problem bitte ein Issue erstellen. Gerne auf die Konversation hier verlinken. Ich habe eine Vermutung und würde dann einen Feature-Branch erstellen.

2023-08-04 07:26 UTC, LKuemmel approved these changes

2023-08-04 07:28 UTC, merged

2023-08-08 20:47 UTC, weichenb commented
@Flock82 :
Danke für den ersten Entwicklungsschritt!
Abfrage funktioniert laut Log-File, Ergebnis wird aber nicht im Frontend angezeigt.

`2023-08-08 22:44:42,868 - {urllib3.connectionpool:973} - {DEBUG:fetch soc_ev5} - Starting new HTTPS connection (1): prd.eu-ccapi.kia.com:8080
2023-08-08 22:44:42,868 - {urllib3.connectionpool:973} - {DEBUG:fetch soc_ev5} - Starting new HTTPS connection (1): prd.eu-ccapi.kia.com:8080
2023-08-08 22:44:43,079 - {urllib3.connectionpool:452} - {DEBUG:fetch soc_ev5} - https://prd.eu-ccapi.kia.com:8080 "GET /api/v1/spa/vehicles/dfdbda51-cd87-4d17-9fb5-d75cfc6da717/ccs2/carstatus/latest HTTP/1.1" 200 None
2023-08-08 22:44:43,079 - {urllib3.connectionpool:452} - {DEBUG:fetch soc_ev5} - https://prd.eu-ccapi.kia.com:8080 "GET /api/v1/spa/vehicles/dfdbda51-cd87-4d17-9fb5-d75cfc6da717/ccs2/carstatus/latest HTTP/1.1" 200 None
2023-08-08 22:44:43,091 - {modules.common.store._api:26} - {DEBUG:fetch soc_ev5} - Raw data CarState(soc=52, range=265.0, soc_timestamp=)`

2023-08-09 14:45 UTC, LKuemmel commented
Die Nachricht ist nach der Nachricht im Issue #1075 obsolet? Am besten im Issue weiter behandeln.