backup_clouds-NFS adapter
openWB/core pull request #1055
Opened 2023-07-27 11:18 UTC by rleidner

initial version
configuration via json - I have no vue skills
nfs_share need to look like nfs_server:/exported_path

2023-07-30 09:42 UTC, rleidner commented
In main.py I increased the timeout to 60 sec.
On my pi4 the backup takes 30 sec with a complete data history since Nov 2020. (250MB tar, 15MB gz).

2023-08-04 09:21 UTC, LKuemmel requested changes

2023-08-04 09:21 UTC, LKuemmel commented on packages/main.py
> +    @exit_after(60)
```suggestion
    @exit_after(10)
```
Ich habe die Backup-Erstellung in einen Thread ausgelagert. Damit sollte die Änderung obsolet sein. Du kannst es gerne testen, indem Du ein Rebase auf den aktuellen Master machst.

2023-10-17 07:42 UTC, LKuemmel approved these changes

2023-10-17 08:07 UTC, merged