Modbus-Steuerung
openWB/core pull request #1095
Opened 2023-08-11 10:19 UTC by LKuemmel

stichprobenartig getestet
Server kann nicht beendet werden

2023-08-14 10:49 UTC, benderl requested changes

2023-08-14 10:49 UTC, benderl commented on packages/control/modbusserver.py
> +        chargepoint = data.data.cp_data[f"cp{_get_pos(address, 2)}"]
```suggestion
        chargepoint = data.data.cp_data[f"cp{_get_pos(address, 2) - 1}"]
```
Sollte das Register `10100` nicht Ladepunkt `0` zugeordnet sein?

2023-08-14 10:49 UTC, benderl commented on packages/control/modbusserver.py
> +    elif address > 10099:
```suggestion
    elif 10099 < address < 20000:
```

2023-08-14 10:49 UTC, benderl commented on packages/control/modbusserver.py
> +        _form_int16("llsolllp8", address)
```suggestion
```
Copy/Paste Überbleibsel von 1.9?

2023-08-28 12:25 UTC, LKuemmel commented
Ersetzt durch #1115

2023-08-28 12:25 UTC, closed without merging