add colors theme
openWB/core pull request #1153
Opened 2023-10-07 18:57 UTC by cshagen

Colors theme integriert.

2023-10-08 13:53 UTC, cshagen commented
Ready for merging

2023-10-09 06:51 UTC, benderl requested changes
Danke für das Colors Theme.

Zusätzlich zu den inline Kommentaren solltest Du bitte eine einheitliche Formatierung verwenden. Aktuell nutzt Du je nach Datei Tabs oder 2 bzw. 4 Leerzeichen zur Einrückung. Auch das Dateiende ("final new line") variiert. Am Besten nutzt Du eine `.editorconfig` sowie den in `package.json` definierten `lint` Befehl. Dadurch sollte auf allen Systemen eine einheitliche Formatierung herauskommen. Mit der VUE-Integration in den Linter würden dann auch Probleme wie das vorhandene `v-if in v-for` auffallen.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/assets/js/mqttClient.ts
> +  password: "openWB",
Bitte nicht Port 9001 verwenden. MQTT wird über den Apache getunnelt, daher ist je nach Verbindung Port 80 oder 443 zu verwenden. Siehe auch https://github.com/openWB/openwb-ui-settings/blob/f91ce0c111570f2f0147b4ca50833244ab3fef91/src/App.vue#L45

`endpoint` der Websockets ist `/ws`.

`username` und `password` werden nicht benötigt.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/assets/js/mqttClient.ts
> +  const connectUrl = `ws://${host}:${port}${endpoint}`;
Protokoll ist je nach Verbindung entweder `ws` oder `wss`.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/assets/js/sendMessages.ts
> +  mqttPublish(topic, JSON.stringify(template))
```suggestion
    mqttPublish(topic, JSON.stringify(template))
```

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/assets/logo.svg
Kann gelöscht werden.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/components/mqttViewer/MQTTViewer.vue
> +      )"
`v-for` und `v-if` dürfen nicht im selben Element genutzt werden.
https://vuejs.org/guide/essentials/list.html#v-for-with-v-if

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/components/mqttViewer/mqttClient.ts
> +  password: "openWB",
Siehe mein Kommentar zur anderen MQTT-Verbindung.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/components/mqttViewer/mqttClient.ts
> +  const connectUrl = `ws://${host}:${port}${endpoint}`;
`ws` oder `wss` je nach Verbindung.

2023-10-09 06:51 UTC, benderl commented on packages/modules/web_themes/colors/source/src/components/powerGraph/PGMenu.vue
> +      </div>
```suggestion
```

2023-10-09 15:46 UTC, cshagen commented on packages/modules/web_themes/colors/source/src/assets/js/mqttClient.ts
> +  const connectUrl = `ws://${host}:${port}${endpoint}`;
Angepasst

2023-10-09 15:50 UTC, cshagen commented
Hallo Lutz, danke fürs Reviewen und das Feedback! Ich habe alle Punkte korrigiert. Ausserdem die ESLint-Konfig angepasst und alle Findings korrigiert, sowie prettier über alles laufen lassen. Ich hoffe mal, dass es jetzt passt :).

2023-10-10 10:52 UTC, benderl approved these changes

2023-10-10 10:53 UTC, merged