FEMS Requests combined to avoid timeouts
openWB/core pull request #1262
Opened 2023-11-18 12:41 UTC by sthhs

My FEMS (Fenecon Home 10, Version 2022 and later) is very sensitive with answering requests at the REST/JSON interface. Too many requests lead to very long answering times (30 s or more) and therefore to timeouts in the OpenWB. In the OpenEMS community you can find that there is indeed a limitation for not overloading the FEMS. The impact on the OpenWB is shown on the attached picture. 
<img width="1342" alt="Timeouts" src="https://github.com/openWB/core/assets/113436006/e03e9de5-93fa-47df-93b7-888315d3283d">
With my modifications (combining of the requests in inverter.py, bat.py, counter.py) and increasing the timeout value in counter.py to 6 almost all of the peaks (occurences of timeouts that lead to the wrong calculation of the consumption) disappear. They aren't gone totally, but reduced to a very small quantity.

2023-11-19 09:03 UTC, sthhs commented
Here are two more pictures.
Without the modification:
<img width="1357" alt="before" src="https://github.com/openWB/core/assets/113436006/97eb02b5-8364-4acc-af58-cac14b29689b">
and with:
<img width="1342" alt="after" src="https://github.com/openWB/core/assets/113436006/88076bdd-e3d3-41b7-9465-3cab8aa75898">

2023-11-21 12:03 UTC, LKuemmel commented on packages/modules/devices/fems/bat.py
> +
```suggestion

```

2023-11-21 12:05 UTC, LKuemmel requested changes

2023-11-21 12:05 UTC, LKuemmel commented on packages/modules/devices/fems/bat.py
> +
```suggestion

```
Please remove, GitHub is already tracking changes

2023-11-21 12:05 UTC, LKuemmel commented on packages/modules/devices/fems/counter.py
> +            #         exported = scale_metric(singleValue['value'], singleValue.get('unit'), 'Wh')
```suggestion
```

2023-11-21 12:05 UTC, LKuemmel commented on packages/modules/devices/fems/inverter.py
> +        # exported = scale_metric(response["value"], response.get("unit"), 'Wh')
```suggestion
```

2023-11-21 16:51 UTC, sthhs commented
Changes completed

2023-11-29 07:33 UTC, LKuemmel approved these changes

2023-12-01 13:59 UTC, LKuemmel commented
Bitte noch die Flake8-Änderungen vornehmen, damit der Test durchläuft.

2023-12-01 14:00 UTC, LKuemmel requested changes
Bitte noch die Flake8-Änderungen vornehmen, damit der Test durchläuft.

2023-12-01 15:23 UTC, sthhs commented
Danke für den Hinweis, die Korrekturen sind gemacht.

2023-12-01 16:04 UTC, sthhs commented
Die Antworten stehen jeweils unter der Abfrage:

**inverter.py:**
http://'+self.ip_address+':8084/rest/channel/_sum/(ProductionActivePower|ProductionActiveEnergy)

`[
    {
        "address": "_sum/ProductionActiveEnergy",
        "type": "LONG",
        "accessMode": "RO",
        "text": "",
        "unit": "Wh_Σ",
        "value": 18988374
    },
    {
        "address": "_sum/ProductionActivePower",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "Total production; always positive",
        "unit": "W",
        "value": -9
    }
]`

**counter.py:**
'http://' + self.ip_address +':8084/rest/channel/(meter0|_sum)/' + '(ActivePower.*|VoltageL.|Frequency|Grid.+ActiveEnergy)'

`[
    {
        "address": "meter0/ActivePowerL3",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "W",
        "value": 6141
    },
    {
        "address": "meter0/ActivePower",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "W",
        "value": 17189
    },
    {
        "address": "meter0/ActivePowerL1",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "W",
        "value": 5575
    },
    {
        "address": "meter0/ActivePowerL2",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "W",
        "value": 5473
    },
    {
        "address": "meter0/VoltageL1",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "mV",
        "value": 229500
    },
    {
        "address": "meter0/VoltageL2",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "mV",
        "value": 229300
    },
    {
        "address": "meter0/VoltageL3",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "mV",
        "value": 229300
    },
    {
        "address": "meter0/Frequency",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "mHz",
        "value": 50000
    },
    {
        "address": "_sum/GridSellActiveEnergy",
        "type": "LONG",
        "accessMode": "RO",
        "text": "",
        "unit": "Wh_Σ",
        "value": 11752059
    },
    {
        "address": "_sum/GridBuyActiveEnergy",
        "type": "LONG",
        "accessMode": "RO",
        "text": "",
        "unit": "Wh_Σ",
        "value": 1088853
    }
]
`
**bat.py:**
"http://" + self.ip_address + ":8084/rest/channel/(ess0|_sum)/" + "(Soc|DcChargeEnergy|DcDischargeEnergy|GridActivePower|ProductionActivePower|ConsumptionActivePower)"

`[
    {
        "address": "_sum/ConsumptionActivePower",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "W",
        "value": 17183
    },
    {
        "address": "_sum/ProductionActivePower",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "Total production; always positive",
        "unit": "W",
        "value": -9
    },
    {
        "address": "_sum/GridActivePower",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "Grid exchange power. Negative values for sell-to-grid; positive for buy-from-grid",
        "unit": "W",
        "value": 17164
    },
    {
        "address": "ess0/Soc",
        "type": "INTEGER",
        "accessMode": "RO",
        "text": "",
        "unit": "%",
        "value": 6
    },
    {
        "address": "ess0/DcChargeEnergy",
        "type": "LONG",
        "accessMode": "RO",
        "text": "",
        "unit": "Wh_Σ",
        "value": 3013394
    },
    {
        "address": "ess0/DcDischargeEnergy",
        "type": "LONG",
        "accessMode": "RO",
        "text": "",
        "unit": "Wh_Σ",
        "value": 3202108
    }
]`

2024-01-02 15:27 UTC, LKuemmel commented
Sorry, ich habe mich lange nicht gemeldet. Ich habe die Tests erstellt bzw angepasst und war so frei, sie in Deinen Branch zu pushen. Danke für deine Beispieldaten!

2024-01-02 15:27 UTC, LKuemmel approved these changes

2024-01-02 15:27 UTC, merged

2024-01-11 20:14 UTC, dj3mu commented on packages/modules/devices/fems/bat.py
> +            "http://" + self.ip_address + ":8084/rest/channel/(" + data + "|_sum)/" +
Sorry, but this change breaks queries on older FEMS versions.

At least on my FEMS v 2022.12.5 a query with Regex in any "segment" other than the last one is NOT supported. FEMS just returns:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://<IP>:8084/rest/channel/(meter0%7C_sum)/(ActivePower.*%7CVoltageL.%7CFrequency%7CGrid.+ActiveEnergy)`

I also see the optimization done here. But I might not be the only one with older version. Actually I have no control on if and when Fenecon updates my FEMS.

So I have no other idea but reverting this!