Polestar soc
openWB/core pull request #1430
Opened 2024-02-19 08:43 UTC by isomacM

SOC module for Polestar2 added

- fix for wrong imports in _simcounter_store.py (please check, if correct)
- changed some log.error to log.info in internal_chargepoint_handler/clients.py (please check, if correct)

Philipp

2024-03-22 13:28 UTC, LKuemmel requested changes
Bitte grundsätzlich nicht mehrere Themen in einem PR mischen.

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
Die Fehlerbehandlung passt noch nicht. So wie es jetzt implementiert ist, werden keine Fehlermeldungen im Frontend angezeigt, sondern nur im Log.
Exceptions werden mit dem Kontextmanager abgefangen https://github.com/openWB/core/blob/a29f40ecaf06ca2a95b12d63805051a546c13a02/packages/modules/common/configurable_vehicle.py#L60 Dieser loggt diese und sendet eine entsprechende Meldung an den Broker, die vom frontend angezeigt wird.

Damit nicht bei einem kurzen Serverausfall sofort die Ladung gestartet wird, gibt es einen Error-Counter, der den SoC zurücksetzt. https://github.com/openWB/core/blob/a29f40ecaf06ca2a95b12d63805051a546c13a02/packages/modules/update_soc.py#L57

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +            return None
```suggestion
            self.auth.delete_token()
           raise Exception("query_params error: get response %d: unauthorized Exception", result.status_code)
        if result.status_code != 200:
            raise Exception("query_params error: get response %d: %s", result.status_code, result.text)

        result_data = result.json()
        if result_data.get('errors'):
            error_message = result_data['errors'][0]['message']
            raise Exception("query_params error: %s", error_message)
```
Hier macht es Sinn, die weitere Verarbeitung abzubrechen und eine Exception zu heben.

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +            return None
Muss die Exception hier abgefangen werden? Wenn keine weitere Fehlerbehandlung erfolgt, macht es Sinn, die Exception vom Kontextmanager behandeln zu lassen.

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +                return None
```suggestion
                raise Exception("No vehicles found using specified account. Did you use the Polestar owners account?")
```
Hier auch eine Exception werfen, dann kommt die Meldung auch im Frontend beim Benutzer an.
Bitte dann auch eine deutsche Meldung, da das Frontend auf Deutsch ist.

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +            return None
```suggestion
                raise Exception("You probably specified a wrong VIN. We only found:%s", ",".join(vins))
```

2024-03-22 13:28 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +        est_range = 0
```suggestion
        soc = bat_data['batteryChargeLevelPercentage']
        est_range = bat_data['estimatedDistanceToEmptyKm']
```
Das zurücksetzen bei misslungener Abfrage erfolgt zentral.

2024-03-25 08:29 UTC, isomacM commented on packages/modules/internal_chargepoint_handler/clients.py
Wenn diese Meldungen für euch so wichtig sind, dass sie immer geloggt werden sollen, ist das ok.

Die Änderungen in den beiden Module _simcounter_store.py und client.py habe ich zurückgenommen.

2024-03-25 08:29 UTC, isomacM commented on packages/modules/vehicles/polestar/soc.py
Du meinst soc_test.py, oder? Das habe ich entfernt.

2024-03-25 08:32 UTC, isomacM commented on packages/modules/vehicles/polestar/api.py
> +            return None
Einverstanden

2024-03-25 08:37 UTC, isomacM commented on packages/modules/vehicles/polestar/api.py
> +                return None
Ok, ich bin mit dem Github Web Interface nicht so vertraut, wie kann ich die deutsche Übersetzung einpflegen?

2024-03-25 08:37 UTC, isomacM commented on packages/modules/vehicles/polestar/api.py
> +            return None
Ok

2024-03-25 08:38 UTC, isomacM commented on packages/modules/vehicles/polestar/api.py
> +        est_range = 0
Verstanden

2024-03-25 09:48 UTC, LKuemmel commented on packages/modules/vehicles/polestar/api.py
> +                return None
```suggestion
                raise Exception("Es konnten keine Fahrzeuge im Account gefunden werden. Bitte in den Einstellungen prüfen, ob der Besitzer-Account des Polestars eingetragen ist.")
```

2024-03-26 15:31 UTC, isomacM commented
Muss ich jetzt noch was machen, oder passt das so?

2024-03-27 12:45 UTC, LKuemmel commented
Es ist nicht möglich, einzelne Softwarekomponenten unter einer eigenen Lizenz zu veröffentlichen. Unsere Software unterliegt der GNU GENERAL PUBLIC LICENSE Version 3: [Link zur Lizenz](https://github.com/openWB/core/blob/master/LICENSE). Bitte überprüfe, ob du deinen Code unter dieser Lizenz veröffentlichen möchtest, und entferne dann die Lizenz aus deinem Pull Request.

2024-03-27 12:57 UTC, isomacM commented
Das war eh die GNU Lizenz, ich habe sie jetzt rausgenommen

2024-03-27 12:59 UTC, LKuemmel commented
Bitte nicht unsere Lizenz löschen, sondern die im Polestar-Ordner...

2024-03-27 14:08 UTC, isomacM commented
Sorry, da war ich wohl etwas zu schnell - sollte jetzt passen 😄

2024-04-03 11:59 UTC, LKuemmel approved these changes

2024-04-03 12:03 UTC, LKuemmel commented
Bitte noch die eine Zeile kürzen, damit die Formatierung passt und der Test durchläuft.

2024-04-03 16:00 UTC, isomacM commented
Hallo,
die Zeile ist jetzt gekürzt - hoffentlich passt es jetzt

2024-04-04 12:27 UTC, merged