fix: chargepoint payload check
openWB/core pull request #1450
Opened 2024-03-03 09:24 UTC by tpd-opitz

#### Problem:
2024-03-03 06:37:56,095 - {helpermodules.setdata:339} - {ERROR:Setdata} - Payload ungültig: Topic openWB/set/chargepoint/6/get/power_factors, Payload 100.0 liegt in keinem der angegebenen Wertebereiche.

#### fix:
 indentation of else block

2024-03-03 16:56 UTC, tpd-opitz commented
rebase auf aktuellen master

2024-03-06 13:53 UTC, LKuemmel requested changes
Das löst nicht das Problem. Es werden Werte zwischen -1 und 1 für den Leistungsfaktor erwartet. Evtl passt hier ein Faktor nicht?

Dein Vorschlag bewirkt, dass bei einer Liste von gültigen Werten bei einem Bereich, in dem der Wert nicht liegt, valid auf False gesetzt wird und danach nicht mehr auf True, wenn noch ein gültiger Bereich kommt.
Der else-Zweig gehört aber zur for-Schleife. Wenn alle ranges in der Liste durchgegangen wurden, wird der Payload als ungültig bewertet.

2024-03-06 14:12 UTC, tpd-opitz commented
OK, verstehe ich.

Was ich nicht verstehe ist, warum der else-Zweig ausgeführt wird, obwohl die Werte korrekt sind...

2024-03-07 14:19 UTC, tpd-opitz commented
Ich habe mal ausgegebe, gegen welche Ranges der Powerfactor geprüft wird:
```
2024-03-07 15:18:17,194 - {helpermodules.setdata:339} - {ERROR:Setdata} - Payload ungültig: Topic openWB/set/chargepoint/5/get/power_factors, Payload 100.0 liegt in keinem der angegebenen Wertebereiche: [(-1, 1)]
```
Das passt tatsächlich nicht.... ;o)

2024-03-07 16:01 UTC, benderl commented
Sind das unterschiedliche Zählertypen? Zufällig ain ABB B23 an dem zweiten LP?

2024-03-07 16:10 UTC, tpd-opitz commented
Nein, sind 2 identische MPM3, wie Sie Kevin in die allerersten OWBs eingebaut hat.

2024-03-11 08:51 UTC, benderl commented
Wird mit #1467 behoben.

2024-03-11 08:51 UTC, closed without merging