mqtt für openwb 2.0
openWB/core pull request #1570
Opened 2024-04-18 11:39 UTC by okaegi

Neu können auch Temp. übergeben werden.
Brauchte noch ein Anpasung in setdata da sonst topics grad wieder gelöscht. Nur für Openwb 2.0
Gui kommt noch separat.
Siehe auch:
https://forum.openwb.de/viewtopic.php?t=8415

2024-04-18 12:09 UTC, LKuemmel requested changes

2024-04-18 12:09 UTC, LKuemmel commented on packages/helpermodules/setdata.py
> +                    # diese topics werden im Smarthomemodul mqtt bearbeitet
```suggestion
                    self._validate_value(msg, None)
```

2024-04-18 14:56 UTC, okaegi commented on packages/helpermodules/setdata.py
> +                    pub_single(msg.topic, "", no_json=True, port=1886)
der self._validate_value(msg, None) ersetzt leider nicht die beiden pub_single..Wenn ich diese beiden durch den   self._validate_value(msg, None) ersetzte, stimmt dann der Payload nicht mehr (m.e. fehlt im _validate_value der  decode("utf-8") auf den payload und ich habe dann im smarthomehandler für das topic device_name "Stiebelx" statt stiebelx

2024-04-18 14:56 UTC, okaegi commented on packages/helpermodules/setdata.py
> +                    # diese topics werden im Smarthomemodul mqtt bearbeitet
ist geändert

2024-04-19 07:08 UTC, LKuemmel commented on packages/helpermodules/setdata.py
> +                    pub_single(msg.topic, "", no_json=True, port=1886)
Ok

2024-04-19 07:08 UTC, LKuemmel approved these changes

2024-04-19 07:10 UTC, merged