smarthome temperatur sensoren
openWB/core pull request #1580
Opened 2024-04-21 09:52 UTC by okaegi

Nur für openwb 2.0 übernehmen
Neu werden temperaturtopics  (TemperatureSensor0/1/2) explizit im mqtt geschlöscht wenn nicht mehr gebraucht. Das vereinfacht das daily log im Json

2024-04-21 10:11 UTC, tpd-opitz commented on packages/smarthome/smartcommon.py
> +            # client.publish(key, payload=value, qos=0, retain=True)
Ich würde das löschen, nicht nurauskommentiern...

2024-04-21 10:11 UTC, tpd-opitz commented on packages/smarthome/smartcommon.py
> +                        # client.publish(key, payload=value, qos=0, retain=True)
Ich würde das löschen, nicht nurauskommentiern...

2024-04-21 10:11 UTC, tpd-opitz commented on packages/smarthome/smartcommon.py
> +def on_message(client: Any, userdata: Any, msg: Any) -> None:
Ist `Any` wirklich hilfreicehr  als gar keine Typangabe?

2024-04-21 10:11 UTC, tpd-opitz commented on packages/smarthome/smartcommon.py
> +def on_connect(client: Any, userdata: Any, flags: Any, rc: Any) -> None:
Ist `Any` wirklich hilfreicehr  als gar keine Typangabe?

2024-04-21 10:29 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +            # client.publish(key, payload=value, qos=0, retain=True)
done

2024-04-21 10:30 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +def on_message(client: Any, userdata: Any, msg: Any) -> None:
da wo ich es kenne hab ich es geändert

2024-04-21 10:30 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +def on_connect(client: Any, userdata: Any, flags: Any, rc: Any) -> None:
da wo ich es kenne hab ich es geändert

2024-04-21 10:31 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +                        # client.publish(key, payload=value, qos=0, retain=True)
done

2024-04-25 07:26 UTC, benderl requested changes
Ich denke auch, dass `Any` hier keinen Sinn macht und auch für das Typechecking keine Vorteile bringt. Dann lieber komplett weg lassen.
Ein paar andere Typen habe ich als Vorschlag ergänzt.

2024-04-25 07:26 UTC, benderl commented on packages/smarthome/smartcommon.py
> +from typing import Any, Dict, List, Tuple
```suggestion
from typing import Dict, List, Tuple
```

2024-04-25 07:26 UTC, benderl commented on packages/smarthome/smartcommon.py
> +def on_connect(client: mqtt.Client, userdata: Any, flags: Dict, rc: Any) -> None:
```suggestion
def on_connect(client: mqtt.Client, userdata, flags: Dict, rc: int) -> None:
```

2024-04-25 07:26 UTC, benderl commented on packages/smarthome/smartcommon.py
> +def on_message(client: mqtt.Client, userdata: Any, msg: Any) -> None:
```suggestion
def on_message(client: mqtt.Client, userdata, msg: mqtt.MQTTMessage) -> None:
```

2024-04-25 10:34 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +from typing import Any, Dict, List, Tuple
mach ich

2024-04-25 10:36 UTC, okaegi commented on packages/smarthome/smartcommon.py
> +def on_message(client: mqtt.Client, userdata: Any, msg: Any) -> None:
mach ich

2024-04-25 10:53 UTC, benderl approved these changes

2024-04-25 11:31 UTC, merged