bmw-SOC-Module: fix authentication issue
openWB/core pull request #1589
Opened 2024-04-26 19:33 UTC by rleidner

fix authentication issue

2024-04-27 17:11 UTC, rleidner commented
Wäre gut wenn der PR bald in den master/nightly kommt, damit die BMW-Fahrer das testen können. :-)

2024-04-29 09:38 UTC, benderl requested changes
Danke für die Anpassung!
Die Anmerkungen bitte auch in dem zweiten PR berücksichtigen.

2024-04-29 09:38 UTC, benderl commented on packages/modules/vehicles/bmw/api.py
> +        os.system("sudo chmod 0777 " + storeFile + ', error=' + str(e))
Bitte keine Ausführungsrechte für eine Datendatei setzen.
```suggestion
        os.chmod(storeFile, 0o666)
    except Exception as e:
        os.system("sudo chmod 0666 " + storeFile + ', error=' + str(e))
```

2024-04-29 09:38 UTC, benderl commented on packages/modules/vehicles/bmw/api.py
> +        apiKey = b'NGYxYzg1YTMtNzU4Zi1hMzdkLWJiYjYtZjg3MDQ0OTRhY2Zh'
Macht es nicht Sinn, den API-Key zum schnelleren Auffinden auch ganz am Anfang als Konstante anzulegen?

2024-04-29 09:38 UTC, benderl commented on packages/modules/vehicles/bmw/api.py
> +            'x-user-agent': 'android(TQ2A.230405.003.B2);bmw;3.11.1(29513);0'}
Der User-Agent und x-user-agent wird mehrfach im Code verwendet. Auch hier macht eine Konstante am Anfang Sinn.

2024-04-29 09:38 UTC, benderl commented on packages/modules/vehicles/bmw/api.py
> +            print("Unknown VIN")
Warum `print()` und kein ordentliches Logging? Übriggeblieben vom Debuggen?

2024-04-29 10:14 UTC, rleidner commented on packages/modules/vehicles/bmw/api.py
> +        os.system("sudo chmod 0777 " + storeFile + ', error=' + str(e))
ist geändert.

2024-04-29 10:15 UTC, rleidner commented on packages/modules/vehicles/bmw/api.py
> +        apiKey = b'NGYxYzg1YTMtNzU4Zi1hMzdkLWJiYjYtZjg3MDQ0OTRhY2Zh'
ich habe alle diese Werte jetzt als Konstante definiert.

2024-04-29 10:15 UTC, rleidner commented on packages/modules/vehicles/bmw/api.py
> +            'x-user-agent': 'android(TQ2A.230405.003.B2);bmw;3.11.1(29513);0'}
s.o

2024-04-29 10:20 UTC, rleidner commented
Im PR für die 1.9 mache ich das gleich

2024-04-29 10:25 UTC, benderl approved these changes

2024-04-29 13:24 UTC, merged