Phasenumschaltung
openWB/core pull request #1644
Opened 2024-05-29 12:47 UTC by pama87

Problem:
Die Einstellung zur Verzögerung der Phasenumschaltung befindet sich unter dem Punkt Ladeeinstellungen Phasenumschaltung und ist nur sichtbar, wenn diese auf Automatik gestellt ist. Zudem beeinflusst die Verzögerung aber auch das Zielladen, welche diese Einstellung allerdings in den Optionen Ladeeinstellungen -> Zielladen nicht bietet. Die Phasenumschaltung in PV-Laden beeinflusst nicht die Phasenumschaltung beim Zielladen, auch nicht, wenn im Modus Zielladen mit PV-Überschuss geladen wird.

Lösung:
Die Einstellung Verzögerung der Phasenumschaltung wandert in die Option Übergreifendes und kann dort immer eingestellt werden, wobei sich diese Einstellung auf PV-Laden sowie Zielladen auswirkt. Dazu wurde:
1. Das topic geändert
2. phase_switch_delay in die Klasse ChargemodeConfig migriert (von PVCharging)
3. bei der Klasse ScheduledCharging phases_to_use_pv hinzugefügt
4. topic phases_to_use_pv hinzugefügt
5. Abfrage in General.py abgeändert, sodass beim Zielladen im Submode PV-Laden die Phasenanzahl der neuen Einstellung berücksichtigt wird

Dadurch lässt sich die Phasenumschaltung im Modus Zielladen bei PV-Überschuss nun unter Ladeeinstellungen-> Zielladen einstellen

2024-06-03 10:35 UTC, pama87 commented
Meinst du wie in Zeile 191, das topic in den Defaults (Z 495) auf den aktuellen slider Wert setzen?

2024-06-03 10:35 UTC, pama87 commented
> Die Änderungen passen soweit. Bitte noch in der update_config.py (ähllich wie in Z 1195) die Einstellung für die Umschaltverzögerung in das neue Topic übernehmen. Sonst ist nach dem Mergen wieder der Standard-Wert gesetzt.

Meinst du wie in Zeile 191, das topic in den Defaults (Z 495) auf den aktuellen slider Wert setzen?

2024-06-03 11:44 UTC, LKuemmel approved these changes

2024-06-25 11:06 UTC, LKuemmel requested changes

2024-06-25 11:06 UTC, LKuemmel commented on packages/helpermodules/update_config.py
> +            if re.search("^openWB/general/chargemode_config/phase_switch_delay$", topic) is not None:
```suggestion
            if re.search("^openWB/general/chargemode_config/pv_charging/phase_switch_delay$", topic) is not None:
```

2024-06-25 11:06 UTC, LKuemmel commented on packages/helpermodules/update_config.py
> +            if re.search("^openWB/general/chargemode_config/phase_switch_delay$", topic) is not None:
```suggestion
            if re.search("^openWB/general/chargemode_config/pv_charging/phase_switch_delay$", topic) is not None:
```
Die if-Abfrage sucht nach dem alten Topic.

2024-06-25 11:11 UTC, pama87 commented on packages/helpermodules/update_config.py
> +            if re.search("^openWB/general/chargemode_config/phase_switch_delay$", topic) is not None:
wurde angepasst. Danke

2024-06-25 11:12 UTC, LKuemmel approved these changes

2024-06-25 11:12 UTC, merged