Smart-hello Vehicle SoC
openWB/core pull request #1653
Opened 2024-06-05 21:24 UTC by MartinRinas

2024-06-06 09:04 UTC, MartinRinas commented
UI: https://github.com/openWB/openwb-ui-settings/pull/481

2024-06-07 13:03 UTC, MartinRinas commented
Bereit für ein Review. Tokencache fehlt noch, den muss ich noch bauen, kommt dann ggf. in einem separaten PR. Das Modul läuft seit in paar Tagen bei mir ganz gut und ruft fleissig den SoC & Range vom Smart #1 ab. Mit den letzten Änderungen sind auch transiente Fehler adressiert.

2024-06-07 13:04 UTC, MartinRinas commented
@LKuemmel kann ich Dich um ein Review bitten?

2024-06-12 09:49 UTC, MartinRinas commented
> Du hast die Änderungen vom letzten Review noch nicht eingepflegt ;)

uhm, ich seh hier kein Review bzw. Kommentare? Hast Du die schon abgeschickt oder hängen die noch irgendwo auf dem Weg?

2024-06-12 09:50 UTC, LKuemmel requested changes

2024-06-12 09:50 UTC, LKuemmel commented
Sorry, das war noch "Pending".

2024-06-12 19:33 UTC, MartinRinas commented on packages/modules/vehicles/smarthello/api.py
> +        raise Exception("Login failed no session found")
hab' ich angepasst und das extra logging entfernt. Die if & raise exceptions werden benötigt das der HTTP request zwar erfolgreich ist, aber dennoch nicht die benötigten Daten enthält. Das ist mir ein paar Mal passiert, hier scheint es gelegentlich unerwartete Ergebnisse zu geben.

2024-06-14 08:44 UTC, LKuemmel approved these changes

2024-06-17 12:29 UTC, merged