Wiki
openWB/core pull request #1658
Opened 2024-06-10 18:54 UTC by sreinhold95

Ergänzung der Doku für die Einrichtung des Huawei Smartloggers 3000a

2024-06-14 11:49 UTC, LKuemmel requested changes

2024-06-14 11:49 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +Zunächts müssen auf dem Smartlogger300a folgdene Einstellungen festgelegt wernden
```suggestion
Im Smartlogger300a müssen folgende Einstellungen festgelegt werden:
```

2024-06-14 11:49 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +    Kann man jetzt die logische Adr. der einzelnen Geräte ablesen. Diese wird dann untern den Einstellungen in der openWB gebraucht (ModbusID)
```suggestion
    Kann man jetzt die logische Adresse der einzelnen Geräte ablesen. Diese wird dann in der openWB in der Einstellung ModbusID eingetragen.
```

2024-06-14 11:49 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +4. in den Einstellungen der openWB das Modus Huawei Smartlogger auswählen.
```suggestion
4. in den Einstellungen der openWB das Modul Huawei Smartlogger auswählen.
```

2024-06-14 11:49 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +6. Hetezt die passenden Komponenten hinzufügen und die jeweilige ModbusID eintragen.
```suggestion
6. Jetzt die passenden Komponenten hinzufügen und die jeweilige ModbusID eintragen.
```

2024-06-14 11:49 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +7. Zum schluss auf Speichern drücken und unter dem Lastmanagement die Passenden Andordnung wählen.
```suggestion
7. Zum Schluss auf Speichern drücken und unter dem Lastmanagement die passende Anordnung wählen.
```

2024-06-14 12:02 UTC, sreinhold95 commented on docs/Huawei-Smartlogger.md
> +Zunächts müssen auf dem Smartlogger300a folgdene Einstellungen festgelegt wernden
Sehe gerade es muss Smartlogger3000a heisen

2024-06-14 12:05 UTC, sreinhold95 commented on docs/Huawei-Smartlogger.md
> +    Kann man jetzt die logische Adr. der einzelnen Geräte ablesen. Diese wird dann untern den Einstellungen in der openWB gebraucht (ModbusID)
```suggestion
    kann man jetzt die logische Adresse. der einzelnen Geräte ablesen. Diese wird dann in der openWB in der Einstellung ModbusID eingetragen.
```

2024-06-14 12:07 UTC, sreinhold95 commented on docs/Huawei-Smartlogger.md
> +Zunächts müssen auf dem Smartlogger300a folgdene Einstellungen festgelegt wernden
```suggestion
Im Smartlogger3000a müssen folgende Einstellungen festgelegt werden:
```

2024-06-14 12:10 UTC, sreinhold95 reviewed
so passt es

2024-06-17 11:02 UTC, LKuemmel requested changes

2024-06-17 11:02 UTC, LKuemmel commented on docs/Huawei-Smartlogger.md
> +    kann man jetzt die logische Adresse. der einzelnen Geräte ablesen. Diese wird dann in der openWB in der Einstellung ModbusID eingetragen.
```suggestion
    kann man jetzt die logische Adresse der einzelnen Geräte ablesen. Diese wird dann in der openWB in der Einstellung ModbusID eingetragen.
```

2024-06-25 06:04 UTC, LKuemmel approved these changes

2024-06-25 06:06 UTC, merged