disable PSA modul
openWB/core pull request #1672
Opened 2024-06-14 15:50 UTC by MartinRinas

2024-06-14 15:54 UTC, MartinRinas reviewed
Ich habe eine Zeit lang überlegt ob ich das PSA Modul einfach komplett entferne, habe mich dann aber für diese Variante entschieden. Das Modul ist seit Wochen nicht mehr funktionsfähig, und das wird sich nach allem was ich weiß auch nicht mehr ändern.
Da nicht alle im Forum unterwegs sind möchte ich über diesen Weg diejnigen erreichen welche das Modul versuchen zu konfigurieren, oder konfiguriert haben und sich wundern warum das nicht klappt, oder was falsch konfiguriert ist.

Nach dem Sommer werde ich das Modul dann komplett entfernen, möchte dem aber ein wenig Zeit geben damit diese Änderung zumindest auch in ein offizielle Release übernommen wird und somit den gewünschten Effekt hat.

2024-06-14 15:56 UTC, MartinRinas commented
https://github.com/openWB/openwb-ui-settings/pull/490

2024-06-17 11:00 UTC, LKuemmel requested changes

2024-06-17 11:00 UTC, LKuemmel commented on packages/modules/vehicles/psa/api.py
> +    raise Exception("Dieses Modul ist nicht mehr funktionstüchtig. Bitte auf anderen Anbeiter, z.b. Tronity, wechseln.")
```suggestion
    raise Exception("Dieses Modul ist nicht mehr funktionstüchtig, da PSA die Schnittstelle entfernt hat. Bitte zu einem anderen Anbieter, z.B. Tronity, wechseln.")
```

2024-06-17 11:40 UTC, LKuemmel approved these changes

2024-06-17 12:29 UTC, merged