Geraeteliste gruppieren Version 2
openWB/core pull request #1683
Opened 2024-06-19 13:40 UTC by pama87

***Geräteliste gruppieren V2***

Geräte von demselben Hersteller wurden in einen Ordner migriert. 
Dann wurden diese Pfade der module geändert und an die neuen Pfade angepasst. Dazu wurde das Attribut type angepasst (beschreibt den Pfad zum importieren -> Import module)

Es wurde ein weiteres Attribut an jedes device angefügt, welches die Gruppe zuordnet (self.group = group).
Es gibt nun drei Kategorien: openWB, generisch(generic) und Systemhersteller(other).

Im Frontend soll dann die Auswahlliste in Geräte und Komponenten in Gruppen aufgeteilt angezeigt werden.

Ausserdem wurde der Datastore upgedatet. 
Getestet, Stand 19.06.2024

2024-07-08 11:00 UTC, LKuemmel requested changes

2024-07-08 11:00 UTC, LKuemmel commented on packages/modules/devices/fems/config.py
> +                 name: str = "Fenecon/FEMS",
```suggestion
                 name: str = "openEMS, FEMS, CENTURIO 10, Kaco Hy-Control",
```
Ein Kunde weiß wahrscheinlich nicht, dass sein Kaco Wechselrichter die gleiche Schnittstelle wie FEMS hat und wird nicht darunter suchen.

2024-07-08 11:05 UTC, pama87 commented on packages/modules/devices/smrt_me/config.py
> +                 type: str = "smrt_me",
der type beschreibt den Pfad zum Ordner, habe den Ordnername geändert, da smart "sma" enthält und die Filterfunktion im frontend such nach dem string in group (sma.other). Man müsste entweder eine kompliziertere Filterfunktion (.includes("sma") für die Anzeige der Geräteliste im Frontend implementieren oder die Namen der Hersteller im Frontend hardcoden (zweite zu pflegende Liste).

2024-07-08 11:06 UTC, pama87 commented on packages/modules/devices/smrt_me/config.py
> +                 type: str = "smrt_me",
> Warum hast Du hier den typ geändert?

der type beschreibt den Pfad zum Ordner, habe den Ordnername geändert, da smart "sma" enthält und die Filterfunktion im frontend such nach dem string in group (sma.other). Man müsste entweder eine kompliziertere Filterfunktion (.includes("sma") für die Anzeige der Geräteliste im Frontend implementieren oder die Namen der Hersteller im Frontend hardcoden (zweite zu pflegende Liste).

2024-07-08 11:09 UTC, pama87 commented on packages/modules/devices/fems/config.py
> +                 name: str = "Fenecon/FEMS",
> Ein Kunde weiß wahrscheinlich nicht, dass sein Kaco Wechselrichter die gleiche Schnittstelle wie FEMS hat und wird nicht darunter suchen.

Ok, d.h. damit der Herstellername sauber unter Hersteller im Frontend angezeigt wird, sollte da dann openEMS/FEMS/Centurio/Kaco hin?

2024-07-09 14:20 UTC, LKuemmel commented on packages/modules/devices/fems/config.py
> +                 name: str = "Fenecon/FEMS",
Ja, bitte.

2024-07-10 10:14 UTC, pama87 commented on packages/modules/devices/fems/config.py
> +                 name: str = "Fenecon/FEMS",
> Ja, bitte.

Erledigt.

2024-07-10 10:21 UTC, pama87 commented on packages/modules/devices/smrt_me/config.py
> +                 type: str = "smrt_me",
> Warum hast Du hier den typ geändert?

Wurde rückgängig gemacht. Funktioniert jetzt ohne Namensänderung

2024-07-18 06:01 UTC, benderl requested changes
Ein großes Problem sehe ich bei der Umstrukturierung der Module. Wir haben jetzt zwei mögliche Fälle im Ordner "devices":
1. "Gerätetyp" / 
2. "Hersteller / "Gerätetyp" /
Wenn jetzt ein Hersteller X, der in unseren Modulen mit Variante 1. eingebunden wurde (Gerätetyp "X"), eine neue Serie (Gerätetyp "G2") mit anderer API auf den Markt bringt, müssen wir auf die 2. Struktur umschwenken. Das zieht dann zwangsläufig eine Datenmigration mit sich, da ja die bestehenden Geräte mit `type: "X"` auf `type: "X.G1"` angepasst werden müssen, um auch `type: "G2"` zu ermöglichen.

Langer Rede, kurzer Sinn:
Wenn die Verzeichnisse und Gerätetypen so angepasst werden sollen, dann bitte auch nur eine Struktur verwenden (die 2.). Damit können wir uns in der Zukunft viel Anpassungsaufwand ersparen.

2024-07-18 06:48 UTC, pama87 commented
> Ein großes Problem sehe ich bei der Umstrukturierung der Module. Wir haben jetzt zwei mögliche Fälle im Ordner "devices":
> 
> 1. "Gerätetyp" /
> 2. "Hersteller / "Gerätetyp" /
>    Wenn jetzt ein Hersteller X, der in unseren Modulen mit Variante 1. eingebunden wurde (Gerätetyp "X"), eine neue Serie (Gerätetyp "G2") mit anderer API auf den Markt bringt, müssen wir auf die 2. Struktur umschwenken. Das zieht dann zwangsläufig eine Datenmigration mit sich, da ja die bestehenden Geräte mit `type: "X"` auf `type: "X.G1"` angepasst werden müssen, um auch `type: "G2"` zu ermöglichen.
> 
> Langer Rede, kurzer Sinn: Wenn die Verzeichnisse und Gerätetypen so angepasst werden sollen, dann bitte auch nur eine Struktur verwenden (die 2.). Damit können wir uns in der Zukunft viel Anpassungsaufwand ersparen. Ich fände aber eine Aufteilung in `vendor` und `type` in Verbindung mit der 2. Struktur sinnvoller, wie in einem inline Kommentar geschrieben.

Ok. Wird geändert. Also alle bekommen die Struktur X.G1

2024-07-18 06:51 UTC, pama87 commented on packages/modules/devices/alpha_ess/config.py
> +                 group: str = "other",
Es gibt drei Gruppen: openWB, generisch und Systemhersteller. Die Aufgabe war dieses Attribut als Sortierkennzeichnung einzuführen. Müsste man nicht dann eine zweite Liste im Frontend pflegen, welche die Zuordnung openWB, generisch oder Systemhersteller macht, wenn man dies nicht bereits hier im backend festlegt?

2024-07-18 06:59 UTC, pama87 commented on packages/modules/devices/alpha_ess/config.py
> +                 device: str = "Alle Geräte",
Ich sehe den Punkt auch so. Kann man die Anzeigenamen im frontend anders lösen (ohne eine zweite zu pflegende Liste, was ja unbedingt vermieden werden soll)? Ich habe dieses Attribut zusätzlich eingeführt, da es einige abweichende Bezeichnungen gibt, z.B.: bei GoodWe steht "GoodWe ET-Serie" oder bei sma steht "SMA Sunny Island, Sunny Tripower X" im String, welcher dann derzeit auch so im frontend angezeigt wird. Ziel war es ie Herstellernamen sauber zu bereinigen, sodass nur diese ind er Liste stehen und wenn ein Hersteller (ohne Zusatzbezeichnung) ausgewählt wird, dass dann die Bezeichnung bei Geräte auftaucht. Wenn man dies nicht als Attribut mitgibt, müsste man dann nicht eine zweite Liste im frontend pflegen? Oder man nimmt sämtliche sonstige Bezeichnungen raus und macht bei allen einfach "Alle Geräte" rein. Was meinst du ist sinnvoller?

2024-07-18 07:07 UTC, pama87 commented on packages/modules/devices/huawei/huawei/config.py
> +                 type: str = "huawei.huawei",
Die Ordnerstruktur in Python im backend wird durch "." getrennt (configuration.py Z186 ff) oder? Wird nicht der type als Pfadspezifikator genutzt um das Modul einzulesen? Man könnte gerne noch einen zusätzliches Attribut einführen mit vendor und Herstellernamen, wäre das dann aber nicht doppelt, wenn man dann 3 Attribute (name, vendor, type) hätte, die alle fast gleich (type = "huawei.huawei" für den Modulimport, vendor = "huawei", name=" huawei smartlogger") heissen?

2024-07-25 13:48 UTC, pama87 commented on packages/modules/devices/huawei/huawei/config.py
> +                 type: str = "huawei.huawei",
Wurde hinzugefügt in configurable_devices

2024-07-25 13:49 UTC, pama87 commented on packages/modules/devices/alpha_ess/config.py
> +                 device: str = "Alle Geräte",
device wurde entfernt.

2024-07-25 13:49 UTC, pama87 commented on packages/modules/devices/alpha_ess/config.py
> +                 group: str = "other",
> Macht es Sinn, die Gruppe variabel zu gestalten? Kann ein Modul unter "others" und in einer anderen Konstellation unter einer anderen Gruppe aufgeführt sein? Falls nicht, kann der Parameter hier entfallen und einfach eine Konstante in der Klasse gesetzt werden.

wurde entfernt.

2024-07-31 09:54 UTC, closed without merging