soc module for OVMS
openWB/core pull request #1743
Opened 2024-07-10 17:28 UTC by rleidner

new soc module for OVMS.
UI: https://github.com/openWB/openwb-ui-settings/pull/506

2024-07-18 10:18 UTC, LKuemmel requested changes

2024-07-18 10:18 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +        log.debug("soc=" + str(self.soc) + ", range=" + str(self.range) + ", soc_ts=" + str(self.soc_ts))
```suggestion
```
Wird modulübergreifend geloggt.

2024-07-18 10:18 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +    return utc + offset
```suggestion
```
Der Code wird niemals aufgerufen.

2024-07-18 10:18 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +        self.vehicle = vehicle
```suggestion
        self.vehicle = vehicle
        self.config = config
```

2024-07-18 10:18 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +        status_url = status_url + "&password=" + self.token
```suggestion
        status_url = f"{OVMS_SERVER}{STATUS_CMD}/{self.vehicleId}?username={self.user_id}&password={self.token}"
```

2024-07-18 10:18 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +        log.debug("status_code=" + str(status_code) + ", response=" + dumps(respDict, indent=4))
```suggestion
        resp = req. get_http_session().get(status_url)
        respDict = loads(resp.text)
```

2024-07-18 17:11 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +    return sed
ist entfernt

2024-07-18 17:13 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +        log.debug("soc=" + str(self.soc) + ", range=" + str(self.range) + ", soc_ts=" + str(self.soc_ts))
Das lasse ich erst mal, weil hier der Zeitstempel gelogged wird an dem das Fahrzeug zum letzten mal Daten an den OVMS-Server übermittelt hat, das wird modulübergreifend leider nicht gelogged.

2024-07-18 17:13 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +    return utc + offset
ist raus

2024-07-18 17:13 UTC, rleidner commented on packages/modules/vehicles/ovms/config.py
> +                     sort_keys=True, indent=4)
ist raus

2024-07-18 17:14 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +        log.debug("token resp.text=" + str(resp.text))
ist geändert

2024-07-18 17:14 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +            log.exception("write_json_file: " + self.replyFile + " Exception " + str(e))
ist raus

2024-07-18 17:16 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +        update_vehicle_config(self.vehicle, confUpdDict)
ist geändert

2024-07-18 17:17 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +initialToken = '1.2.3'
ist raus

2024-07-18 17:18 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +    return
ist raus

2024-07-18 17:18 UTC, rleidner commented on packages/modules/vehicles/ovms/api.py
> +        self.vehicle = vehicle
ist geändert

2024-07-18 17:26 UTC, rleidner commented
Zusätzlich neu eingebaut: 
a) wenn get_status auf Fehler geht, wird ein neuer token erzeugt.
Das könnte passieren, wenn der gespeicherte token im OVMS-Server gelöscht wird.
b) Der Range kommt vom OVMS manchmal um Faktor 10 zu hoch, z.B. 1023.0 km statt 102,3 km. Das wird jetzt korrigiert, wenn range > 800km.

2024-07-19 09:45 UTC, LKuemmel commented on packages/modules/vehicles/ovms/api.py
> +        log.debug("token resp.text=" + str(resp.text))
Bitte nochmal schauen, Du verwendest immer noch requests.post statt common.req.get_http_session().post() .

2024-07-19 09:58 UTC, LKuemmel commented
> d) req.get_http_session().get/post kann leider nicht benutzt werden, da nach einem Fehler keine Fehlerbehandlung mehr möglich ist. Daher wieder zurück auf requests.

Was passiert denn dann? Wenn der Statuscode zwischen 400 und 600 liegt, wird eine Exception geworfen, die Du abfangen kannst und sonst kann Du auf den Statuscode mit `.status_code` zugreifen.

2024-07-19 10:37 UTC, rleidner commented
Danke für den Hinweis. Ist jetzt umgestellt auf req.get_http_session().get/post und exception handling.

2024-07-23 09:49 UTC, LKuemmel approved these changes

2024-09-10 10:57 UTC, merged