add possibility to invert external inverter power
openWB/core pull request #1794
Opened 2024-07-31 10:41 UTC by ndrsnhs

https://github.com/openWB/openwb-ui-settings/pull/525

2024-08-14 08:36 UTC, ndrsnhs commented on packages/helpermodules/update_config.py
> +                    and "factor" not in payload["configuration"]:
Meldung von 3 Partnern zum Problem. Zählerstände der Wechselrichter sehen mit 14.945,639kWh, 33.649,736kWh und 23.469,904kWh erstmal plausibel aus. (Sollte das Import sein hätten die WR einen sehr hohen Eigenverbrauch...)
Was nicht gesichert ist: Handelt es sich um ein generelles Problem, dann kann man sich die Auswahl im UI ggfs sparen. Das Modul gibt es schon länger, die Fehlermeldungen sind neu. Wird das Vorzeichen pauschal umgekehrt besteht das Risiko, dass Bestandsanlagen die laufen falsche Werte liefern.

2024-08-14 10:02 UTC, LKuemmel approved these changes

2024-08-22 09:16 UTC, benderl approved these changes

2024-09-04 10:40 UTC, LKuemmel requested changes

2024-09-04 10:40 UTC, LKuemmel commented on packages/helpermodules/update_config.py
> +    self.__update_topic("openWB/system/datastore_version", 55)
Die Einrückung muss noch um eins nach vorne. Und bitte noch den Konflikt beheben. Im Kommentar steht noch GoodWe.

2024-09-12 07:08 UTC, merged