OCPP
openWB/core pull request #1893
Opened 2024-09-18 09:58 UTC by LKuemmel

2024-10-02 09:14 UTC, LKuemmel commented
braucht Rebase nach Merge von #1912, damit der Test läuft

2024-10-08 10:02 UTC, benderl requested changes

2024-10-08 16:09 UTC, LKuemmel commented on packages/main.py
> +from control import optional
umgesetzt

2024-10-08 16:09 UTC, LKuemmel commented on packages/helpermodules/update_config.py
> +        ("openWB/optional/ocpp/active", False),
umgesetzt

2024-10-08 16:09 UTC, LKuemmel commented on packages/control/optional_data.py
> +    url: str = ""
umgesetzt

2024-10-08 16:09 UTC, LKuemmel commented on packages/control/optional.py
> +            self.ocpp_boot_notification_send = False
umgesetzt

2024-10-08 16:09 UTC, LKuemmel commented on packages/control/optional.py
> +                    self.ocpp_boot_notification_send = True
umgesetzt

2024-10-08 16:09 UTC, LKuemmel commented on packages/control/ocpp_test.py
> +    assert data.data.optional_data.ocpp_boot_notification_send is True
umgesetzt

2024-10-08 16:10 UTC, LKuemmel commented on packages/helpermodules/setdata.py
> +                self._validate_value(msg, str)
umgesetzt

2024-10-08 16:10 UTC, LKuemmel commented on packages/helpermodules/update_config.py
> +        "^openWB/optional/ocpp/version$",
umgesetzt

2024-10-08 17:29 UTC, benderl approved these changes

2024-10-10 06:58 UTC, merged

2024-10-10 08:46 UTC, gerdemann commented
I have tested these changes with our OCPP backend and it looks like it keeps establishing a new websocket connection, sending the request and then closing it again. Can't the connection be permanent?