soc_bmwbc: add new captcha for initial login
openWB/core pull request #2035
Opened 2024-11-23 13:49 UTC by rleidner

Support new captcha required by BMW server login
Store token file in folder data/bmwbc instead of ramdisk to avoid too frequent captcha process after reboot.
related UI PR: https://github.com/openWB/openwb-ui-settings/pull/589

2024-11-23 18:24 UTC, benderl requested changes

2024-11-23 18:24 UTC, benderl commented on packages/modules/vehicles/bmwbc/api.py
> +dataPath = "/var/www/html/openWB/data/bmwbc"
Bitte keinen absoluten Pfad verwenden. Analog zu `RAMDISK_PATH` sollte es auch eine Konstante für das Wurzelverzeichnis der Installation geben, habe ich aber gerade nicht im Kopf. Alternativ das Verzeichnis relativ zur aktuellen Datei ermitteln.

2024-11-23 19:38 UTC, rleidner commented on packages/modules/vehicles/bmwbc/api.py
> +dataPath = "/var/www/html/openWB/data/bmwbc"
Ist erledigt. Die Konstante habe ich auch nicht gefunden, ist jetzt relativ.

2024-12-02 11:14 UTC, benderl requested changes

2024-12-02 11:14 UTC, benderl commented on packages/modules/vehicles/bmwbc/api.py
> +DATA_PATH = "data/bmwbc"
Es ist einfacher, wenn Du mit dem Path-Objekt arbeitest.
```suggestion
DATA_PATH = Path(__file__).resolve().parents[4] / "data" / "bmwbc"
```

2024-12-02 11:14 UTC, benderl commented on packages/modules/vehicles/bmwbc/api.py
> +                  dataPath + ", error=" + str(e))
```suggestion
        log.debug("dataPath=" + str(DATA_PATH))
        DATA_PATH.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        log.error("init: dataPath creation failed, dataPath: " +
                  str(DATA_PATH) + ", error=" + str(e))
```

2024-12-02 11:45 UTC, rleidner commented on packages/modules/vehicles/bmwbc/api.py
> +                  dataPath + ", error=" + str(e))
Ich habe es bei mir so geändert, getestet und ein neues commit gemacht.

2024-12-02 11:45 UTC, rleidner commented on packages/modules/vehicles/bmwbc/api.py
> +DATA_PATH = "data/bmwbc"
Ich habe es bei mir so geändert, getestet und ein neues commit gemacht.

2024-12-02 11:56 UTC, benderl approved these changes

2024-12-11 12:53 UTC, Meli73 commented
In OWB1 nightly It works fine with Captcha.
Is there already a way to test it here in OWB2?   in Alpha, Beta or Release ?

2024-12-12 14:37 UTC, merged

2024-12-12 14:58 UTC, Meli73 commented
tried it , but got this:

2024-12-12 14:53:19,334 - {modules.vehicles.bmwbc.api:49} - {WARNING:fetch soc_ev6} - load_store: store file not found, full authentication required
2024-12-12 14:53:19,335 - {modules.vehicles.bmwbc.api:143} - {ERROR:fetch soc_ev6} - bmwbc.fetch_soc: requestData Error, vnum: 6 err=TypeError("__init__() got an unexpected keyword argument 'hcaptcha_token'"), type(err)=<class 'TypeError'>
2024-12-12 14:53:19,369 - {modules.common.fault_state:49} - {ERROR:fetch soc_ev6} - BMW (Bimmer): FaultState FaultStateLevel.ERROR, FaultStr <class 'TypeError'> ("__init__() got an unexpected keyword argument 'hcaptcha_token'",), Traceback: 
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/modules/common/configurable_vehicle.py", line 66, in update
    car_state = self._get_carstate_by_source(vehicle_update_data, source)
  File "/var/www/html/openWB/packages/modules/common/configurable_vehicle.py", line 110, in _get_carstate_by_source
    return self.__component_updater(vehicle_update_data)
  File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/soc.py", line 20, in updater
    return api.fetch_soc(
  File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/api.py", line 156, in fetch_soc
    soc, range = loop.run_until_complete(_fetch_soc(user_id, password, vin, captcha_token, vnum))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/api.py", line 101, in _fetch_soc
    auth = MyBMWAuthentication(user_id,
TypeError: __init__() got an unexpected keyword argument 'hcaptcha_token'

2024-12-12 16:25 UTC, rleidner commented
> tried it , updated to 2.1.7-Alpha.1 2024-12-12 15:49:02 +0100 [[1927094](https://github.com/openWB/core/commit/192709443f5040ba102c1377b36e2ad50d7c2ff3)]
> 
> but got this:
> 
> 2024-12-12 14:53:19,334 - {modules.vehicles.bmwbc.api:49} - {WARNING:fetch soc_ev6} - load_store: store file not found, full authentication required 2024-12-12 14:53:19,335 - {modules.vehicles.bmwbc.api:143} - {ERROR:fetch soc_ev6} - bmwbc.fetch_soc: requestData Error, vnum: 6 err=TypeError("**init**() got an unexpected keyword argument 'hcaptcha_token'"), type(err)=<class 'TypeError'> 2024-12-12 14:53:19,369 - {modules.common.fault_state:49} - {ERROR:fetch soc_ev6} - BMW (Bimmer): FaultState FaultStateLevel.ERROR, FaultStr <class 'TypeError'> ("**init**() got an unexpected keyword argument 'hcaptcha_token'",), Traceback: Traceback (most recent call last): File "/var/www/html/openWB/packages/modules/common/configurable_vehicle.py", line 66, in update car_state = self._get_carstate_by_source(vehicle_update_data, source) File "/var/www/html/openWB/packages/modules/common/configurable_vehicle.py", line 110, in _get_carstate_by_source return self.__component_updater(vehicle_update_data) File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/soc.py", line 20, in updater return api.fetch_soc( File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/api.py", line 156, in fetch_soc soc, range = loop.run_until_complete(_fetch_soc(user_id, password, vin, captcha_token, vnum)) File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete return future.result() File "/var/www/html/openWB/packages/modules/vehicles/bmwbc/api.py", line 101, in _fetch_soc auth = MyBMWAuthentication(user_id, TypeError: **init**() got an unexpected keyword argument 'hcaptcha_token'

The PR is now merged - please update to  latest master.

2024-12-12 20:42 UTC, Meli73 commented
you mean :
updated to 2.1.7-Alpha.1 2024-12-12 15:49:02 +0100 [[1927094](https://github.com/openWB/core/commit/192709443f5040ba102c1377b36e2ad50d7c2ff3)]

I did already..  or is there somthing newer  ?

2024-12-12 20:48 UTC, rleidner commented
> you mean : updated to 2.1.7-Alpha.1 2024-12-12 15:49:02 +0100 [[1927094](https://github.com/openWB/core/commit/192709443f5040ba102c1377b36e2ad50d7c2ff3)]
> 
> I did already.. or is there somthing newer ?

That version should be working; if you continue to have issues, you get support in the openwb forum. 
I can't maintain support on 2 different platforms; therefore I will not respond here from now on.