Aiways SoC module
openWB/core pull request #2066
Opened 2024-12-15 21:34 UTC by FriedrichF

Auf Basis dieser Anleitung https://community.home-assistant.io/t/read-aiways-u5-state-of-charge/466441/5 habe ich ein SoC Modul für Aiways geschrieben.
Es ist zwar etwas Aufwändiger an die Nutzerdaten zu gelangen, aber diese sind dafür sehr lange gültig.

2025-01-02 11:32 UTC, LKuemmel requested changes
Kannst Du bitte auch eine Einstellungs-Seite im Settings-Repo erstellen? eine Anleitung findest Du hier: https://github.com/openWB/core/wiki/Einstellungs-Seite-erstellen Bei Fragen gerne melden.

2025-01-02 11:32 UTC, LKuemmel commented on packages/modules/vehicles/aiways/soc.py
> +user_agent = "okhttp/4.3.1"
Unser Code ist nach dem Python Style Guide formatiert, dh globale Variablen werden mit GROßBUCHSTABEN benannt. Oder Du setzt die Werte direkt im Header, es wird ja nur einmal auf die Variablen zugegriffen.

2025-01-04 21:11 UTC, FriedrichF commented
Habe die Variablen direkt in die Headers.
Zudem ist hier der PR für das UI https://github.com/openWB/openwb-ui-settings/pull/611

2025-01-09 07:37 UTC, LKuemmel approved these changes

2025-01-09 07:37 UTC, merged