improve logging, store refreshToken in soc configuration
openWB/core pull request #655
Opened 2022-11-17 20:56 UTC by rleidner

logging: script prepare_libvwid.sh modifies logging to write to soc.log in debug level

Token handling: Optimizations to avoid reconnect after restart
- split storage of refreshToken and accessToken.
- refreshToken is stored in mqtt 
- accessToken is stored in ramdisk file.
- SOC configuration extended by refreshToken, 
- The refreshToken is stored in hex/ascii coded form. 
- the refrreshToken is completely maintained by the module and shall not be shown in configuration-UI

2022-11-18 14:00 UTC, rleidner commented
Not working as expected.

2022-11-27 11:14 UTC, rleidner commented
Lena, Lutz,
den Konflikt in requirements.txt bekomme ich nicht weg.
Soll ich da etwas machen, wenn ja,, was?
Gibt es sonst Bedenken bei diesem PR?

2022-11-29 07:09 UTC, benderl commented
Bei solchen Konflikten hilft eigentlich immer ein `git rebase master`. Dadurch werden Deine neuen Commits in der History auf den aktuellen Stand verschoben und neu angewandt. Dabei kannst Du dann die Konflikte beheben und anschließend den Branch mit `git push origin <branch> --force` auf Github aktualisieren.

Wir beheben zuerst ein Problem mit dem Dienststart, wenn neue Abhängigkeiten hinzukommen (#672). Dann kann der PR rein. Den Konflikt kann ich auch hier beheben, wenn Du es bis dahin noch nicht geschafft hast. Ist ja übersichtlich.

2022-11-29 07:29 UTC, LKuemmel requested changes

2022-11-29 07:29 UTC, LKuemmel commented on packages/modules/vehicles/vwid/api.py
> +        f.close()
Hier bitte auch das Python-Logging verwenden.

2022-11-29 07:29 UTC, LKuemmel commented on packages/modules/vehicles/vwid/libvwid.py
> +            self.log.debug("vwid.libvwid: Login error: %s", json_model['errorCode'])
Das Python-Logging ist so konfiguriert, dass das Modul, aus dem die Logmeldung stammt, und das zugehörige Fahrzeug in der Lognachricht enthalten sind.
```suggestion
            self.log.error("Login error: %s", json_model['errorCode'])
```
Die vorherige Einstufung in Error war richtig, da es sich hier ja um einen Fehler handelt, sollte er auch als solcher geloggt werden.

2022-11-29 20:03 UTC, rleidner commented
Lena, Lutz,
die Änderungen sind jetzt gemacht.
Es wird nur noch logging verwendet für Teile der response vom VW-server.
Der Konflikt in requirements.txt ist beseitigt.

Weitere Änderungen:
api.py ist auf eine Klasse umgestellt.
Einige Hilfsfunktionen sind in ein neues Modul bzw. Klasse  socutils.py/socUtils ausgelagert:
Lesen, Speichern und Handling der JWT-Token.
Das könnte auch für andere SOC-Module nützlich  sein.

2022-11-30 14:13 UTC, LKuemmel requested changes

2022-11-30 14:13 UTC, LKuemmel commented on packages/modules/vehicles/vwid/socutils.py
> +            log.debug('Token file write exception ' + str(e))
```suggestion
            log.exception('Token file write exception ' + str(e))
```

2022-11-30 14:13 UTC, LKuemmel commented on packages/modules/vehicles/vwid/socutils.py
> +            log.debug('Token mqtt write exception ' + str(e))
```suggestion
            log.exception('Token mqtt write exception ' + str(e))
```

2022-11-30 14:13 UTC, LKuemmel commented on packages/modules/vehicles/vwid/soc.py
> +            log.info("Result: soc=" + str(soc)+", range=" + str(range))
Die Logmeldung ist nicht nötig, self.store.set loggt die Werte bereits.
```suggestion
```

2022-11-30 14:13 UTC, LKuemmel commented on packages/modules/vehicles/vwid/socutils.py
> +            log.debug('get_token_expiration error ' + str(e))
```suggestion
            log.exception('get_token_expiration error ' + str(e))
```

2022-11-30 14:13 UTC, LKuemmel commented on packages/modules/vehicles/vwid/api.py
> +                log.debug("refreshToken initialization exception: set refreshToken_old to initial value")
```suggestion
                log.exception("refreshToken initialization exception: set refreshToken_old to initial value")
```
Bei Level Error/Exception werden die Fehler in jedem Fall geloggt. Wird der Fehler als Level Exception geloggt, ergänzt das Python-Logging automatisch Exception-Infos. (Level Exception darf nur im except-Zweig verwendet werden)
(betrifft auch weitere Exceptions in dieser Datei)

2022-12-06 10:55 UTC, merged