soc SmartEQ: initial version
openWB/core pull request #683
Opened 2022-12-07 21:41 UTC by rleidner

SOC Modul for Smart EQ
Delivers soc & range for smart EQ vehicles

2022-12-09 13:10 UTC, LKuemmel requested changes

2022-12-09 13:10 UTC, LKuemmel commented on packages/modules/vehicles/smarteq/api.py
> +    async def _fetch_soc(self,
Warum hast Du die Methode mit dem Keyword async versehen? Hier wird doch gar nichts asynchron ausgeführt.
Die einzelnen SoC-Modul werden übrigens in Threads abgefragt.

2022-12-09 13:10 UTC, LKuemmel commented on packages/modules/vehicles/smarteq/api.py
> +            self.Tokens = pickle.load(tf)
Bitte am Python-Style-Guide orientieren: Klassen-Namen beginnen mit einem Großbuchstaben, Variablen und Attribute mit Kleinbuchstaben.

2022-12-09 13:10 UTC, LKuemmel commented on packages/modules/vehicles/smarteq/api.py
> +class api:
Bitte am Python-Style-Guide orientieren: Klassen-Namen beginnen mit einem Großbuchstaben, Variablen und Attribute mit Kleinbuchstaben.
```suggestion
class Api:
```

2022-12-09 18:20 UTC, rleidner commented
Changes re style guide committed

2022-12-12 14:41 UTC, LKuemmel requested changes

2022-12-12 14:41 UTC, LKuemmel commented on packages/modules/vehicles/smarteq/api.py
> +bASE_URL = "https://id.mercedes-benz.com"
```suggestion
BASE_URL = "https://id.mercedes-benz.com"
```
Die Schreibweise mit den Großbuchstaben war richtig, da es Konstanten sind. Diese werden in Python mit GROSSBUCHSTABEN benannt.

2022-12-13 09:33 UTC, LKuemmel approved these changes

2022-12-13 09:34 UTC, merged