Huawei smartlogger
openWB/core pull request #841
Opened 2023-03-11 18:13 UTC by sreinhold95

2023-03-11 18:20 UTC, sreinhold95 commented
Modul für Huawei Smartlogger, nicht für den Dongle, da andere Register für den EVU Zähler
läuft seit 1,5 Wochen bei mir Stabil im Test. 
Device Einstellung ist IP Adresse
und pro Komponente die ModBus_ID.
Batterie konnte ich leider nicht testen. habe keine.

2023-03-13 16:27 UTC, LKuemmel requested changes
Ich hoffe, Dich erschlägt mein Review nicht. Bei Fragen gerne kommentieren!

2023-03-13 16:27 UTC, LKuemmel commented on .github/workflows/manual-workflow.yml
> +          PYTHONPATH=packages python -m pytest packages --log-cli-level=DEBUG
Ich habe den Workflow freigeschaltet. Damit kann die Datei weg.

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/config.py
> +                 type: str = "huawei_smartlogger",
```suggestion
class HuaweiSmartlogger:
    def __init__(self,
                 name: str = "Huawei Smartlogger",
                 type: str = "huawei_smartlogger",
```
Naming bitte anhand der Python-Konvention: Klassen mit CamelCase (ohne Unterstrich)

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/config.py
> +                 name: str = " Huawei Luna",
Muss es unbedingt ein Huawei Luna Speicher sein? Oder passt als Beschreibung "Huawei Speicher"?

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/config.py
> +        self.ip_address = ip_address
Ist im Smartlogger der Port einstellbar? Dann macht es Sinn, ihn auch hier in die Einstellungen aufzunehmen.

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/counter.py
> +        self.component_config = dataclass_from_dict(Huawei_SmartloggerCounterSetup, component_config)
```suggestion
        self.component_config = component_config
```

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/bat.py
> +        self.component_config = dataclass_from_dict(Huawei_SmartloggerBatSetup, component_config)
```suggestion
        self.component_config = component_config
```

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/inverter.py
> +        self.component_config = dataclass_from_dict(Huawei_SmartloggerInverterSetup, component_config)
```suggestion
        self.component_config = component_config
```

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/device.py
> +class Device(AbstractDevice):
Das Huawei-Modul, das Du wahrscheinlich als Vorlage genommen hast, verwendet noch die Device-Klasse. Unter [https://github.com/openWB/core/blob/master/docs/samples/sample_modbus/device.py](https://github.com/openWB/core/blob/master/docs/samples/sample_modbus/device.py) ist die aktuelle Vorlage, so wird der Code viel übersichtlicher. Kannst Du das bitte umstellen? 
Im Wiki findest Du auch eine Beschreibung zur Vorlage: [https://github.com/openWB/core/wiki/Neues-Gerät-programmieren](https://github.com/openWB/core/wiki/Neues-Gerät-programmieren)

2023-03-13 16:27 UTC, LKuemmel commented on packages/modules/devices/huawei_smartlogger/bat.py
> +                 component_config: Union[Dict, Huawei_SmartloggerBatSetup],
```suggestion
                 component_config: Huawei_SmartloggerBatSetup,
```

2023-03-13 18:06 UTC, sreinhold95 commented
Hallo,
theoretisch möglich.
Hatte es der übersichtlichkleit halber als extra Gerät programmiert, das es keine Verwechslung gibt.
Die Modbus Register der Wechselrichter sind auch die gleichen. 
Es unterscheidet sich der SmartMeter und nach Test evtl. die Batterie.
Ob die Batterie funktioniert kann ich nicht sagen, da ich wie gesagt keine Habe. 
Am SmartDongle würden die Abfragen auch funktionieren, dort müssten aber Pausen eingebaut werden, da dieser sonst abstürzt. 
Der Smartlogger braucht auch keine ca. 7 Sec sleep um die Verbindung zu öffnen am Anfang, wie der SmartDongle. 
Er trennt diese per Timeout, wenn zu lange keine Anfrage kommt.
Das war auch der Grund warum ich den Smartlogger gekauft habe.

2023-06-04 09:27 UTC, sreinhold95 commented
Habe heute nochmals im Code geschaut,
durch den 7 Sec sleep im Huawei Device geht es leider nicht, das man alles in eins packt.
kann man den Pull Request so wie er ist mergen oder spricht eurer seits noch was dagegen, was unbedingt geändert werden muss?
das Device läuft seit dem Pull Reqeust Datum Fehlerfrei.

2023-07-19 08:50 UTC, LKuemmel commented
Bitte die Datei .github/workflows/manual-workflow.yml aus dem PR entfernen, dann der PR so rein.

2023-07-20 13:50 UTC, sreinhold95 commented
Die datei ist draußen

2023-07-24 06:42 UTC, LKuemmel approved these changes

2023-07-24 06:42 UTC, merged