add support info
openWB/core pull request #986
Opened 2023-06-29 10:39 UTC by benderl

collect some hardware info on boot

2023-06-29 12:54 UTC, LKuemmel commented
In die send_debug.sh, zB Z51 muss noch 
```
	echo "############################ uuids ##############"
	cat "${OPENWBBASEDIR}/data/log/uuid.log"
```

2023-06-29 12:55 UTC, LKuemmel requested changes
In die send_debug.sh, zB Z51 muss noch 
```
	echo "############################ uuids ##############"
	cat "${OPENWBBASEDIR}/data/log/uuid.log"
```

2023-06-29 13:37 UTC, LKuemmel commented
Das UUID-Log sollte beim Zurücksetzen auch nicht gelöscht werden.

2023-06-30 06:12 UTC, benderl commented
> In die send_debug.sh, zB Z51 muss noch
> 
> ```
> 	echo "############################ uuids ##############"
> 	cat "${OPENWBBASEDIR}/data/log/uuid.log"
> ```

Ist integriert.

2023-06-30 06:13 UTC, benderl commented
> Das UUID-Log sollte beim Zurücksetzen auch nicht gelöscht werden.

Wurde es auch bis jetzt nicht.
Habe aber noch ein potentielles Problem in dem Skript `factory_reset.sh` behoben und die Größe des `uuid.log` beschränkt.

2023-06-30 06:56 UTC, LKuemmel approved these changes

2023-06-30 07:10 UTC, merged